# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
units: bin/units.tsv
# path or URL to contrast sheet (TSV format, columns: sample, condition, ...)
contrasts: bin/contrasts.tsv

ref:
  # path/to/reference/gDNA.fasta
  sequence:       /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/c.elegans-WBcel235/sequence/c.elegans-WBcel235.fa
  fai:            /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/c.elegans-WBcel235/sequence/c.elegans-WBcel235.fai
  # path/to/STAR/index/directory
  # index:          /varidata/research/projects/bbc/versioned_references/2021-08-10_11.12.27_v6/data/mm10_gencode/indexes/star
  index: /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/c.elegans-WBcel235/indexes/star
  # salmon_index:
  salmon_index:  /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/c.elegans-WBcel235/indexes/salmon/c.elegans-WBcel235
  # path/to/gtf/file/with/transcripts.gtf
  annotation:     /varidata/research/projects/bbc/versioned_references/2022-03-08_14.47.50_v9/data/c.elegans-WBcel235/annotation/c.elegans-WBcel235.gtf
  # known variants (Broad resource downloaded here: https://console.cloud.google.com/storage/browser/genomics-public-data/resources/broad/mm10/v0/)
  known_snps:
  known_indels:
  snpeff_db_id:
# are the sequencing reads paired-end ('PE') or single-end ('SE')
PE_or_SE: PE

# what is the strandedness of the kit used for library prep?
# options: "forward", "reverse", "unstranded" (usually reverse)
strandedness: reverse

### EdgeR Variables ###

# used for annotation. see src/annotation.tsv for common_name options. e.g.:  "mouse", "human", "fly"
common_name: worm
factorA_name: Genotype 
factorB_name: Treatment
# differential expression cutoff values
logfc.filter: 1
fdr.filter: 0.05

# Boolean for whether to call variants. Requires 'variant_calling_units.tsv'
# snpRelate html report only generated if conda is callable. Otherwise, the snpRelate rule is not run.
call_variants: false


sortmerna:
    rfam5_8s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.4-Linux/rRNA_databases/rfam-5.8s-database-id98.fasta
    rfam5s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.4-Linux/rRNA_databases/rfam-5s-database-id98.fasta
    silva_arc_16s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.4-Linux/rRNA_databases/silva-arc-16s-id95.fasta
    silva_arc_23s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.4-Linux/rRNA_databases/silva-arc-23s-id98.fasta
    silva_bac_16s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.4-Linux/rRNA_databases/silva-bac-16s-id90.fasta
    silva_bac_23s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.4-Linux/rRNA_databases/silva-bac-23s-id98.fasta
    silva_euk_18s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.4-Linux/rRNA_databases/silva-euk-18s-id95.fasta
    silva_euk_28s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.4-Linux/rRNA_databases/silva-euk-28s-id98.fasta
    idx_dir: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.4-Linux/indexes/idx/
